name: CI

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash -l {0}

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    env:
      WORKDIR: .
    container:
      image: shawnraul7/femsolver
      options: --user root --privileged
    name: Boost Testing
    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Where am I
        run: pwd

      - name: Build and Test
        run: |
          mkdir build
          cd build
          cmake ..
          make 
          ctest 

